name: Build and push Docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - cli-alpine
          - fpm-alpine
        version:
          - 8.2.28

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push base image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          target: base
          tags: zlatinl1/php:${{ matrix.version }}-${{ matrix.variant }}

      - name: Build and push php with nodejs support
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          target: nodejs
          tags: zlatinl1/php:${{ matrix.version }}-${{ matrix.variant }}-nodejs

      - name: Build and push php with xdebug support
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          target: xdebug
          tags: zlatinl1/php:${{ matrix.version }}-${{ matrix.variant }}-xdebug
